/**
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef Example_ENUM_H
#define Example_ENUM_H

#include <QJsonValue>
#include <QMetaType>
#include <QString>

namespace oapi_example {

class ExampleEnum {
public:
    ExampleEnum() {}

    ExampleEnum(QString jsonString) {
        fromJson(jsonString);
    }

    virtual ~ExampleEnum() {}

    virtual QJsonValue asJsonValue() const {
        return QJsonValue(jstr);
    }

    virtual QString asJson() const {
        return jstr;
    }

    virtual void fromJson(QString jsonString) {
        jstr = jsonString;
    }

    virtual void fromJsonValue(QJsonValue jval) {
        jstr = jval.toString();
    }

    virtual bool isSet() const {
        return false;
    }

    virtual bool isValid() const {
        return true;
    }

private:
    QString jstr;
};

} // namespace oapi_example

Q_DECLARE_METATYPE(oapi_example::ExampleEnum)

#endif // Example_ENUM_H
